# Generated by Django 3.1.3 on 2020-12-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
