# Generated by Django 3.1.2 on 2020-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20201107_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
